# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d396220ca0b8760ae5d3765da9f1c0f5c4cf4802e687f9e3cc673201ac3d8e7dc3c6e3b919514eecd1c75cab6f903acd872b3cc57f469cb0c798926383099a96

test:
  secret_key_base: 6debb6fc43438af07e5ee8244aa9c3980b6576e8490ccfe7789182bd88f14a4d1189241020e3a026d72fca7d5a92b45646024b9ce32b34828bcb69067d7cbf99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
